### ISSUE TITLE
No save option for picture attachment

### ISSUE THREAD

**Issue by sgundumonu** [akoscz/HockeyAppSample#1]
I am testing Hockey App on Moto X running 5.1.
Upon attaching picture to user feedback form there is no option to save.
On Samsung S3 which has physical back, home and options buttons, save option comes upon clicking options button.
Without save option on no hard physical button phone, this feature will have very limited use.
Please fix this.

Thanks,
Sai

**Comment by akoscz** [comment]
Hi Sai,
  Sorry I wont be able to help you with your issue.  The HockeyAppSample is simply a demonstration of how to get up and running with the SDK quickly.
  What you are facing sounds like something that should be part of the HockeyApp SDK.  I recommend you file an issue against the SDK.  https://github.com/bitstadium/HockeySDK-Android/issues

**Comment by sgundumonu** [comment]
Thanks for responding.
